### ISSUE TITLE
PHP 8.0 Compatibility

### ISSUE THREAD

**Issue by abugey** [systopia/de.systopia.campaign#103]
* [x] Analyse code regarding PHP 8 compatibility
* [x] Fix deprecations found (to be specified)

**Comment by abugey** [comment]
linter: no errors
PHPStorm inspect code:
`CampaignExpense.php: Lines 25, 118, 164: undefined constant 'CRM_Financial_BAO_FinancialItem'`

**Comment by jensschuppe** [comment]
Those were straight-forward, I merged the branch. As we're still in alpha, this will have enough implicit testing in the wild anyway. Thanks @abugey!

**Comment by bjendres** [comment]
Looks like this wasn't all, needs to include #104 / #105 by @olayiwola-compucorp
