### ISSUE TITLE
The campaign dashboard does not display campaigns on PHP8

### ISSUE THREAD

**Issue by olayiwola-compucorp** [systopia/de.systopia.campaign#104]
On a server with PHP8 campaigns are not being displayed.
<img width="1207" alt="Screenshot 2022-12-20 at 19 59 55" src="https://user-images.githubusercontent.com/85277674/208745296-fd6039dd-6b67-4b75-b66a-b29e4b153e00.png">

The following errors can be seen in the error log:

> Error: Non-static method CRM_CampaignTree_BAO_Campaign::actionLinks() cannot be called statically in CRM_CampaignTree_BAO_Campaign::getCampaignList() (line 179 of /civicrm/ext/de.systopia.campaign/CRM/CampaignTree/BAO/Campaign.php).

> TypeError: array_key_exists(): Argument #2 ($array) must be of type array, CRM_Campaign_DAO_Campaign given in CRM_CampaignTree_BAO_Campaign::getCampaignList() (line 182 of /civicrm/ext/de.systopia.campaign/CRM/CampaignTree/BAO/Campaign.php).

**Comment by bjendres** [comment]
Thanks for fixing this, @olayiwola-compucorp
