### ISSUE TITLE
Campaign Manager still uses methods which are removed from CiviCRM 5.60

### ISSUE THREAD

**Issue by scardinius** [systopia/de.systopia.campaign#108]
Campaign Manager still uses methods which are removed from CiviCRM 5.60:

`CRM_Core_OptionGroup::getLabel()` → should we use `CRM_Core_PseudoConstant::getLabel()`

`CRM_Core_OptionGroup::getValue()` → should we use `CRM_Core_PseudoConstant::getKey()`

Therefore there are errors trying to view some campaign:

```
Error: Call to undefined method CRM_Core_OptionGroup::getValue() in CRM_Campaign_KPI::getContributionStatusList() 

Error: Call to undefined method CRM_Core_OptionGroup::getLabel() in civicrm_api3_campaign_expense_get() 
```

**Comment by jensschuppe** [comment]
Duplicate of #107

**Comment by scardinius** [comment]
ah, indeed. I was looking around only on issues :(
