### ISSUE TITLE
Campaign Dashboard: replace calls to dead core BAO methods - incompatibility with CiviCRM 5.67+

### ISSUE THREAD

**Issue by jofranz** [systopia/de.systopia.campaign#114]
```
 ------ ----------------------------------------------------------------------------------- 
  Line   CRM/CampaignManager/CampaignTree/Page/Dashboard.php                                
 ------ ----------------------------------------------------------------------------------- 
  104    Call to an undefined static method CRM_Campaign_BAO_Campaign::getCampaignCount().  
  133    Call to an undefined static method CRM_Campaign_BAO_Survey::getSurveyCount().      
  162    Call to an undefined static method CRM_Campaign_BAO_Petition::getPetitionCount().  
 ------ ----------------------------------------------------------------------------------- 
```

Maybe someone can estimate the implications?

_internal ref: 22950_

**Comment by bjendres** [comment]
Probably @jensschuppe would know best at this point.

**Comment by jensschuppe** [comment]
Those are Core methods, why should they be undefined, @jofranz? Have they been removed from Core in a recent version? They might have got moved into the Core *civi_campaign* extension which needs to be installed for *Campaign Manager* to work correctly, though.

**Comment by jofranz** [comment]
I'm always scanning against current master. Looks like they got removed from coleman two weeks ago:

https://github.com/civicrm/civicrm-core/commit/50a6565141ad3e7274968f081b4a61e32141890e

**Comment by jensschuppe** [comment]
I see, they got removed on the current master branch of Core with https://github.com/civicrm/civicrm-core/commit/50a6565141ad3e7274968f081b4a61e32141890e in https://github.com/civicrm/civicrm-core/pull/27271 which seems to be scheduled for 5.67.

**Comment by jensschuppe** [comment]
Those occurrences should be refactored, using the API with `SelectRowCount` as a quick fix. We should also check whether *Campaign Manager*'s dashboard is still useful now that the Core one has moved to *SearchKit*.

**Comment by bjendres** [comment]
> We should also check whether Campaign Manager's dashboard is still useful now that the Core one has moved to SearchKit.

We're not talking about the KPIs here, right? If not, I would agree.

**Comment by jensschuppe** [comment]
Seems to be both, kind of. But removing/adjusting the dashboard would be another issue, anyway.

**Comment by eileenmcnaughton** [comment]
It looks like the plan is to migrate to a new extension - https://github.com/systopia/de.systopia.campaign/issues/112

**Comment by bjendres** [comment]
> It looks like the plan is to migrate to a new extension - #112

Yes, but that's a long term thing. We'll still keep this version around for a while. 

@sluc23 do you have a timeline for your re-implementation?

**Comment by sluc23** [comment]
I have an alpha release, I think i can publish it int 1-2 weeks max.. it has some basic features for now and a different technical approach on some areas, but I'll be happy to hear your comments. 
You can have a preview in the repo https://github.com/ixiam/campaignmanager

Keep you posted.

PS: the idea is to move it to lab.c.org and publish it under the name `campaignmanager`

**Comment by jensschuppe** [comment]
@sluc23 Are there plans for providing a migration path from `de.systopia.campaign` to `campaignmanager`?

**Comment by sluc23** [comment]
@jensschuppe I was checking what to migrate and I don't find much to do.. the KPI part has been completely rewritten using new CiviCRM Entitties instead of using custom cache tables.. I don't see a way to migrate that.. and the rest of features has not been ported yet.

I was thinking on integrating extension [expenses](https://lab.civicrm.org/extensions/expenses), for the expenses part, instead of develop that again, but that would be in a next phase

**Comment by jensschuppe** [comment]
There are at least some settings (that might or might not have to be migrated) and some database tables for activity statistics (if that is enabled), and  the `campaign_expense_types` option group.

But I think you'll know best - maybe you can document your migration from `de.systopia.campaign` to your new extension so that others know what to pay attention to …?
