### ISSUE TITLE
Installation on 5.66 and 5.67.1 with v 1.4.1 not working

### ISSUE THREAD

**Issue by xpdientUK** [systopia/de.systopia.campaign#116]
With CiviCRM 5.67.1 there is no apparent change to the Campaign Dashboard - ie no view link to the extended dashboard.

With CiviCRM 5.66 the Campaign dashboard stalls on a search screen and just hangs there so no campaigns are displayed at all.

**Comment by bjendres** [comment]
Thanks for reporting. @jensschuppe could you have a look?

**Comment by jensschuppe** [comment]
Core converted the *CiviCampaign* dashboard to a *SearchKit* display (civicrm/civicrm-core#27271), so the current implementation of *Campaign Manager* won't work with that anymore. I guess we'll have to declare *Campaign Manager* incompatible with CiviCRM 5.67, as a fix seems non-trivial with the current code of *Campaign Manager*.

You might want to try https://github.com/ixiam/campaignmanager instead, which aims to be a complete re-write of *Campaign Manager*.

**Comment by jensschuppe** [comment]
I'll label the issue `needs funding` and `help wanted` in case anyone wants help/fund to adapt the current code to *SearchKit* etc.
