### ISSUE TITLE
Deprecated parameter type when calling `CRM_Utils_Hook::singleton()->invoke()`

### ISSUE THREAD

**Issue by MarcMichalsky** [systopia/de.systopia.campaign#118]
We see these warnings in our logs:

```
[warning] hook_civicrm_campaignKpis should be updated to pass an array of parameter names to CRM_Utils_Hook::invoke(). Caller: CRM_Utils_CampaignCustomisationHooks::campaign_kpis
Array
(
    [civi.tag] => deprecated
)
```
This line
https://github.com/systopia/de.systopia.campaign/blob/6c0520ec2724182d5783331068292a7d44f95535/CRM/Utils/CampaignCustomisationHooks.php#L20
should be changed as follows:
```php
return CRM_Utils_Hook::singleton()->invoke(["campaign_id", "kpi_list", "level"], $campaign_id, $kpi_list, $level, self::$null, self::$null, self::$null, 'civicrm_campaignKpis');
```

**Comment by bjendres** [comment]
Great, thanks @MarcMichalsky. Two things:

1. Does that affect minimum ~~PHP~~ CiviCRM version (currently ``5.34``)?
2. Would you create a PR?

**Comment by jensschuppe** [comment]
> minimum PHP version (currently 5.34)

minimum CiviCRM version, that is, I guess …

This deprecation notice (which just makes the compatibility code visible) came in with 5.26.0 (see https://github.com/civicrm/civicrm-core/commit/ecb0ae5d0d607a53da2037f7fc618c38e23b81db), so I guess we'd be fine.

**Comment by MarcMichalsky** [comment]
Thanks @jensschuppe for finding the reference!
