### ISSUE TITLE
Visualization of Chart "Revenue Breakdown"

### ISSUE THREAD

**Issue by bkaless** [systopia/de.systopia.campaign#18]
This one is our KPI-Chart:
![revenue_breakdown](https://cloud.githubusercontent.com/assets/7643442/14320555/d3a88352-fc15-11e5-955e-3f31f89ca0a9.jpg)

It would be more readable if the circle contains only numbers from 1 to X. At the bottom of the chart should be a explanation of all campaign-names.

**Comment by bjendres** [comment]
Good idea

**Comment by Cullpepper** [comment]
Name with % of total would be cool. love this extension by the way, well done!

**Comment by Cullpepper** [comment]
Or display pie-wedge name/value on hover.
