### ISSUE TITLE
TreeView breaks structure of campaign

### ISSUE THREAD

**Issue by scardinius** [systopia/de.systopia.campaign#34]
Scenario:

* Open campaign with structure like this: root > only one subcampaign 1 level > [ first 2 level subcampagin, second 2 level subcampaign]
* Click on button `View Campaign Tree`
* Click on campaign *first 2 level subcampaign* or *second 2 level subcampaign*
* Click on button `View Root`
    * Structure is changed :(

**Comment by bjendres** [comment]
Thanks, @scardinius. 

@mattwire Could you have a brief look at this? Does that affect our project as well?

**Comment by mattwire** [comment]
@scardinius: I think this commit fixes your problem? https://github.com/systopia/de.systopia.campaign/commit/d6a179332f956ccc84cbb18c9876c79c59aff36d

If it is working with that fix, I will merge that into master

**Comment by scardinius** [comment]
@mattwire @systopia thanks! That works fine!

**Comment by mattwire** [comment]
Merged commit to master

**Comment by bjendres** [comment]
Great job @mattwire!

One tiny performance remark: we could just check for ``dist <= 900`` to avoid the costly ``Math.sqrt`` function. But it won't have a significant impact in this scenario anyway...
