### ISSUE TITLE
alpha 1.1: detail page empty

### ISSUE THREAD

**Issue by bkaless** [systopia/de.systopia.campaign#36]
I updated to the 1.1alpha1 version because I impatient to see the new overview. Very fine.

But now the detail of a campaign is empty again: for example: civicrm/a/#/campaign/2/view has no content. 
I checked that firebug alerts no error, the partial-directory should be readable.

Best regards
Bene

**Comment by bjendres** [comment]
Sounds like an Angular issue. Is it the same URL as before? What CiviCRM version are you on?

**Comment by bkaless** [comment]
We are on 4.6.28. It is the same url as before. I deactivated the extension, deinstalled the extension, replaced the files in the extension directory with the new ones from git and activated the extension.

**Comment by bjendres** [comment]
Hm, did you clear the cache and run ``/civicrm/menu/rebuild``? 

@mattwire any ideas?

**Comment by bkaless** [comment]
yes, I cleared the cache and now I triggerd /civicrm/menu/rebuild

Sorry, no effect :(

**Comment by bjendres** [comment]
Does the new angular CiviMail interface work for you? Do you have all permissions?

**Comment by bjendres** [comment]
@bkaless Is this possibly related to #38? Could you pull the lates master and test again?

**Comment by BettyDolfing** [comment]
I installed the latest 'master' last week, but got the same error: an empty detail page. Cleared cache, rebuild menu. But did not help. 
I then installed 1.0.beta1 and the detailed page was working. 
Is there anything else I can try or any tips on how to get this working in the latest version?

**Comment by bjendres** [comment]
@BettyDolfing  Do other angular pages work for you? Which CiviCRM version are you on?

**Comment by scardinius** [comment]
Hi @systopia 

I've met the same problem. My CiviCRM is 4.7.23

JavaScript error in console:
"Uncaught TypeError: Cannot set property 'contextMenu' of undefined"

    js/lib/d3-context-menu.js:
    root.d3.contextMenu = factory(root.d3);

I found the solution - I updated this file to current version from https://github.com/patorjk/d3-context-menu/blob/master/js/d3-context-menu.js and it works on my site :-)

I hope it will help you to resolve this issue.

**Comment by bjendres** [comment]
Thanks @scardinius.

@BettyDolfing: Can you confirm that this works?

**Comment by BettyDolfing** [comment]
No, not yet. Tried what @scardinius suggested, but is not working for me. However, could be something is wrong in my environment(s). Will ask our developer to have a look at it. Will come back to you if I have news.

**Comment by jaapjansma** [comment]
@systopia I have tried the solution of @scardinius and it does not work for me. But it also looks like the file d3-context-menu.js is never loaded.

**Comment by jaapjansma** [comment]
@systopia I also get an error in the console: crmEditable undefined.

**Comment by jaapjansma** [comment]
@systopia I found what causes the crmEditable error. Uncommented line 274 in https://github.com/systopia/de.systopia.campaign/blob/master/templates/CRM/CampaignTree/Form/Search.tpl#L274 fixes that error.

Now I have a new error on view a campaign: 'typeError: root.d3 is undefined'

**Comment by jaapjansma** [comment]
I have found the issue I had to add a custom group with the nam e'campaign_information' and now it works.

In short, I have done two things:
1. remove line 274 in CampaignTree/Form/Search.tpl
2. Add a custom group with the name 'campaign_information'

**Comment by jaapjansma** [comment]
One last remark when I disable debug settings in CiviCRM viewing a campaign does not work anymore.

**Comment by bjendres** [comment]
Thanks @jaapjansma. With those modifications, does it work now? @BettyDolfing ?

**Comment by bkaless** [comment]
I installed the alpha1.1 from github, created the group "campaign_information", removed line 274 (as result I have a empty else clause, right?) and enabled the debugging. 

When I now click on campaign -> overview the angular turns endlessly.

**Comment by BettyDolfing** [comment]
Thanks @jaapjansma and @scardinius! It's working for me in CiviCRM 4.7.18,  version 1.1.alpha2. 

Did 3 things: 
1. remove line 274 in CampaignTree/Form/Search.tpl
2. Add a custom group with the name 'campaign_information'
3. Updated file to current version from https://github.com/patorjk/d3-context-menu/blob/master/js/d3-context-menu.js

**Comment by bjendres** [comment]
Brilliant, thank you guys! Would you mind creating a PR for 1 and 3, while I remove this dependency from the `campaign_information` group?

**Comment by jaapjansma** [comment]
Sure I will do that.

**Comment by bjendres** [comment]
Cannot reproduce on 4.6.22 with 1.1.beta1 any more

**Comment by bjendres** [comment]
Cannot reproduce on 4.7.18 with 1.1.beta1 any more

**Comment by scardinius** [comment]
The commit "removed dependency on custom group"
https://github.com/systopia/de.systopia.campaign/commit/959d1077ba93f894710cb5c34973ad062568285e resolved the problem on 4.7.24 with 1.1.beta1
