### ISSUE TITLE
1.1alpha1: Sorting

### ISSUE THREAD

**Issue by bkaless** [systopia/de.systopia.campaign#37]
Ad the moment the list in the overview is not sorted. It would be fine if  the list is sorted by date (newest beginning date first) by default.

**Comment by bjendres** [comment]
@mattwire What was the plan here? Is this list currently sorted by anything?

**Comment by mattwire** [comment]
Currently it is sorted by name ascending by default.  But you can sort by any column by clicking on it.

**Comment by jensschuppe** [comment]
I can confirm default sorting being name ascending. As the table is sortable, looks like won't fix to me.
