### ISSUE TITLE
Viewing campaigns w/o debug mode

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.campaign#39]
@jaapjansma writes:

> One last remark when I disable debug settings in CiviCRM viewing a campaign does not work anymore.

**Comment by bjendres** [comment]
See #36

**Comment by bjendres** [comment]
Cannot reproduce on 4.6.22 with 1.1.beta1

**Comment by bjendres** [comment]
Cannot reproduce on 4.7.18 with 1.1.beta1

**Comment by scardinius** [comment]
Cannot reproduce on 4.7.24 with 1.1.beta1
