### ISSUE TITLE
crmEditable Error

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.campaign#40]
@jaapjansma writes in #36:

> @systopia I also get an error in the console: crmEditable undefined.
> 
> @systopia I found what causes the crmEditable error. Uncommented line 274 in https://github.com/systopia/de.systopia.campaign/blob/master/templates/CRM/CampaignTree/Form/Search.tpl#L274 fixes that error.
> 
> Now I have a new error on view a campaign: 'typeError: root.d3 is undefined'

**Comment by bjendres** [comment]
@jaapjansma says:

> remove line 274 in CampaignTree/Form/Search.tpl

**Comment by bjendres** [comment]
Cannot reproduce on 4.6.22 with 1.1.beta1

**Comment by bjendres** [comment]
**Can reproduce** on 4.7.18 with 1.1.beta1

**Comment by scardinius** [comment]
Can reproduce on 4.7.20 and 4.7.24, the error is slightly different:

`Uncaught TypeError: $(...).crmEditable is not a function`

updating d3-context-menu to new version doesn't resolve the problem :(

comment line `$('.crm-editable').crmEditable();` **resolve the problem** :-)

**Comment by bjendres** [comment]
Commenting out that line doesn't seem to have a negative impact.
