### ISSUE TITLE
Various issues with version 1.1

### ISSUE THREAD

**Issue by Fabian-SYSTOPIA** [systopia/de.systopia.campaign#42]
After installing version 1.1beta1 on an CiviCRM 4.7.24 environment (was able to reproduce it on another environment too) I encountered two issues that should be fixed in that version:
1. crm editable error as described in #40 
2. generated delete link is missing base url 

In addition, the extension seems to break other components that use angular such as the mailing interface (/civicrm/a/#/mailing/new) or the case type page (civicrm/a/#/caseType).

**Comment by jensschuppe** [comment]
@Fabian-SYSTOPIA is 1. still relevant with the latest 1.2-alpha? 2. got fixed in #72. Additionally, the general "breakage" of Angular functionality should be fixed as well.

**Comment by jensschuppe** [comment]
@Fabian-SYSTOPIA This got fixed already in #40.
