### ISSUE TITLE
Load KPIs asynchronously

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.campaign#46]
Don't block the page load.

**Comment by bjendres** [comment]
@kpomaranska: I think I fixed this, could you please verify?

**Comment by kpomaranska** [comment]
@systopia it looks good :)
I was only able to test it on a campaign with 15000 activites, and it was really quick. 
Probably would be good to add an indicator that something is in progress (right now tabs are closed during the calculations, and are opening when the calculations are complete) - if the campaign has larger amount of activities, it could take a bit more time, and the user has no indication that he/she should wait a bit for the calculations to complete.

**Comment by bjendres** [comment]
@kpomaranska Cool, thanks.

Of course we have also thought about the indicator, but i'm running out of time. Could you maybe create an extra ticket for that?
