### ISSUE TITLE
When adding parent to the campaign, it external id is set to null and this is visible on the campaign dashboard

### ISSUE THREAD

**Issue by kpomaranska** [systopia/de.systopia.campaign#48]
when adding parent to the campaign (either while creating a new subcampaign or adding a parent to existing campaign), it external id is set to null and this is visible on the campaign dashboard

**Comment by bjendres** [comment]
@kpomaranska: I think I fixed it, could you verify this, please?

**Comment by kpomaranska** [comment]
@systopia tested, looks good :)

**Comment by bjendres** [comment]
Brillian, thanks @kpomaranska
