### ISSUE TITLE
To edit previously added expense you need to click through all of the expense fields

### ISSUE THREAD

**Issue by kpomaranska** [systopia/de.systopia.campaign#55]
When you create an expense in a campaign, you need to fill all of the fields for the "Submit" button to become active.
When you try to edit previously added expense you need to click through all of the fields to be able to save the changes (the "Submit" button is not active othervise)

**Comment by bjendres** [comment]
@kpomaranska  I think I fixed it, could you please test and verify?

**You will have to clear all CiviCRM/browser caches** to see the effect.

**Comment by kpomaranska** [comment]
@systopia It works :)

**Comment by bjendres** [comment]
Great, another one down. Thanks
