### ISSUE TITLE
View not loading in WordPress

### ISSUE THREAD

**Issue by danaskallman** [systopia/de.systopia.campaign#56]
I am testing this on WordPress and the page just doesn't load. These are the errors I get when I try to View a campaign with this extension enabled. I see `root.d3` and angular errors. 

![angular-d3-errors](https://user-images.githubusercontent.com/1139085/31447563-4cdec32c-ae70-11e7-9aaf-55ecfcd59a7f.png)

Thoughts on why?

**Comment by bjendres** [comment]
Thanks @danaskallman. I have really not a lot of experience with either d3 nor WordPress. Anyone else...?

**Comment by bastienho** [comment]
Hi,

same problem here. 

The `root.d3` error can be solved by upgrading [**d3-context-menu**](https://github.com/patorjk/d3-context-menu/raw/master/js/d3-context-menu.js).

Angular errors are removed after a set of 
```
bower upgrade
composer upgrade
```
in `wp-content/plugins/civicrm/civicrm`.

Nevertheless, the view page is still blank, and no error explains why.

**Comment by bjendres** [comment]
Sorry guys, I really can't help you with this....

**Comment by bastienho** [comment]
ok, but upgrading the lib could be at least, a good thing.

**Comment by bastienho** [comment]
@danaskallman this forked project works in WordPress

**Comment by bastienho** [comment]
@danaskallman this [forked project](https://github.com/scardinius/de.systopia.campaign) works in WordPress

**Comment by danaskallman** [comment]
@bastienho oh cool, let me test it. Thanks!

**Comment by jensschuppe** [comment]
@danaskallman is this still relevant when using the latest 1.2-alpha? Really looks like a duplicate of #36.
