### ISSUE TITLE
Javascript compatibility with 4.7.25

### ISSUE THREAD

**Issue by scardinius** [systopia/de.systopia.campaign#65]
I met some javascript bugs on 4.7.25 version

Cannot use 'in' operator to search for 'false' in null
`if(!"vis_type" in current_item) {`

Cannot read property 'value' of null
`if(Array.isArray(current_item.value)) {`

**Comment by herbdool** [comment]
I'm testing out this extension. I applied this patch but still some JS errors which I'll report on a new issue.

**Comment by scardinius** [comment]
I understood why I had a problem. I use campaignKpis hook in separate extension in wrong way because of latest mods at campaign meneger. It's possible to switch off some metrics but I assumed that all metrics (kpis) are always included.

I fixed my extension and it works fine at 4.7.29 now
