### ISSUE TITLE
1.2.alpha2 fails on install

### ISSUE THREAD

**Issue by bkaless** [systopia/de.systopia.campaign#70]
Installing the 1.1.alpha2 brings the following error in the apache2.log:

PHP Fatal error:  Class 'CRM_Campaign_Config' not found in /var/www/html/sites/default/files/civicrm/ext/de.systopia.campaign/campaign.php on line 45,

**Comment by bkaless** [comment]
Oh, I see this Issues points to the same question: 
https://github.com/systopia/de.systopia.campaign/issues/61

**Comment by jensschuppe** [comment]
Closing as duplicate of #61.
