### ISSUE TITLE
"Average Cost per Second or Later Contribution" has a different meaning than calculated value

### ISSUE THREAD

**Issue by scardinius** [systopia/de.systopia.campaign#8]
Hi,

I'd like to ask what was a aim of this KPI, because description has a different meaning than calculated value :-)

``` php
$second_or_later = $amount_all - $first_contributions;
// get average cost per second or later contribution
$kpi['amount_average_second_or_later'] = array(
  "id" => "amount_average_second",
  "title" => "Average Cost per Second or Later Contribution",
  "kpi_type" => "money",
  "vis_type" => "none",
  "description" => "Average Cost per second or later contribution associated with this campaign",
  "value" => $second_or_later,
  "link" => ""
);
```

[KPI.php:L225](https://github.com/systopia/de.systopia.campaign/blob/master/CRM/Campaign/KPI.php#L225)

**Comment by bjendres** [comment]
> I'd like to ask what was a aim of this KPI, because description has a different meaning than calculated value :-)

Well, the description is what we want: the average cost of a "not first (ever, per contact)" contribution. 

@nikobo: do you want to make a case for your implementation or do you agree that there might be a bug?

**Comment by ghost** [comment]
I think this is a bug, because the line obviously calculates the number of contributions that are not classified as a "first" contribution and not their average _amount_.

**Comment by bjendres** [comment]
@Niko: Is this an easy fix? Or @scardinius: did you have a PR ready?

**Comment by ghost** [comment]
@systopia Fixing this should be trivial

**Comment by scardinius** [comment]
PR #9 is ready.

**Comment by ghost** [comment]
And merged, thanks!

**Comment by bjendres** [comment]
Great!
